name: CI/CD Pipeline for Spring Boot App

# main 브랜치에서 push 되거나 pull request가 열리면 자동 실행
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
	# job 이름: build-and-push
  build-and-push:
    runs-on: ubuntu-latest # ubuntu 가상 머신에서 실행

		# 환경 변수 설정
    env:
      IMAGE_NAME: devsecops-pipeline-test
      REGISTRY: docker.io
      IMAGE_TAG: ${{ github.sha }} # 커밋 해시를 사용해 태그 설정

    steps:
    # 리포지토리 가져오기
    - name: Checkout repository
      uses: actions/checkout@v4

		# OpenJDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

		# Maven을 사용해 애플리케이션 빌드 (.jar 파일 생성)
    - name: Build with Maven
      run: ./mvnw package -DskipTests

		# Docker Hub 로그인
    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          "${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          "${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
